# Generated by Django 2.1.7 on 2019-02-18 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_tracker', '0002_expertisecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelExpertiseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_tracker.ExpertiseCategory')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personnel expertise categories',
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='expertise_categories',
            field=models.ManyToManyField(through='mentor_tracker.PersonnelExpertiseCategory', to='mentor_tracker.ExpertiseCategory'),
        ),
        migrations.AddIndex(
            model_name='personnelexpertisecategory',
            index=models.Index(fields=['personnel', 'expertise_category'], name='mentor_trac_personn_e80193_idx'),
        ),
        migrations.AddIndex(
            model_name='personnelexpertisecategory',
            index=models.Index(fields=['personnel'], name='mentor_trac_personn_e8540b_idx'),
        ),
        migrations.AddIndex(
            model_name='personnelexpertisecategory',
            index=models.Index(fields=['expertise_category'], name='mentor_trac_experti_891b9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personnelexpertisecategory',
            unique_together={('personnel', 'expertise_category')},
        ),
    ]
