# Generated by Django 2.1.7 on 2019-02-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_tracker', '0003_auto_20190218_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField()),
                ('building_number', models.CharField(max_length=20, null=True)),
                ('floor', models.CharField(max_length=15, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['street_address'], name='mentor_trac_street__6fb558_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['building_number'], name='mentor_trac_buildin_2789b5_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['floor'], name='mentor_trac_floor_3f43c0_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['description'], name='mentor_trac_descrip_6359c8_idx'),
        ),
    ]
