# Generated by Django 2.1.7 on 2019-02-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_tracker', '0004_auto_20190218_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='mentor_trac_name_6c09a4_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['description'], name='mentor_trac_descrip_6bd5ed_idx'),
        ),
    ]
