# Generated by Django 2.1.7 on 2019-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_tracker', '0005_auto_20190218_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Example: Apple', max_length=40)),
                ('product', models.CharField(help_text='Example: Galaxy', max_length=40)),
                ('version', models.CharField(help_text='Example: Xs Max', max_length=40)),
                ('uuid', models.CharField(help_text='Example: 00:00:00:00:00:00', max_length=17, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['make'], name='mentor_trac_make_81d605_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['product'], name='mentor_trac_product_d081c9_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['version'], name='mentor_trac_version_6ea169_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['uuid'], name='mentor_trac_uuid_8876d5_idx'),
        ),
    ]
