# Generated by Django 2.1.7 on 2019-02-18 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_tracker', '0006_auto_20190218_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_tracker.Organization')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='organizations',
            field=models.ManyToManyField(through='mentor_tracker.PersonnelOrganization', to='mentor_tracker.Organization'),
        ),
    ]
