# Generated by Django 2.1.7 on 2019-02-18 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_tracker', '0007_auto_20190218_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_tracker.Device')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='devices',
            field=models.ManyToManyField(through='mentor_tracker.PersonnelDevice', to='mentor_tracker.Device'),
        ),
        migrations.AddIndex(
            model_name='personneldevice',
            index=models.Index(fields=['personnel', 'device'], name='mentor_trac_personn_bca35c_idx'),
        ),
        migrations.AddIndex(
            model_name='personneldevice',
            index=models.Index(fields=['personnel'], name='mentor_trac_personn_531279_idx'),
        ),
        migrations.AddIndex(
            model_name='personneldevice',
            index=models.Index(fields=['device'], name='mentor_trac_device__a387ee_idx'),
        ),
        migrations.AddIndex(
            model_name='personneldevice',
            index=models.Index(fields=['tracked'], name='mentor_trac_tracked_bb5d24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personneldevice',
            unique_together={('personnel', 'device')},
        ),
    ]
