# Generated by Django 2.1.7 on 2019-02-18 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_tracker', '0008_auto_20190218_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelLocationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signal_strength', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_tracker.Location')),
            ],
            options={
                'verbose_name_plural': 'Personnel location entries',
            },
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name_plural': 'Personnel'},
        ),
        migrations.AddField(
            model_name='personnel',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentor_tracker.Location'),
        ),
        migrations.AddField(
            model_name='personnellocationentry',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='personnellocationentry',
            index=models.Index(fields=['personnel'], name='mentor_trac_personn_9be849_idx'),
        ),
        migrations.AddIndex(
            model_name='personnellocationentry',
            index=models.Index(fields=['location'], name='mentor_trac_locatio_bcfa47_idx'),
        ),
        migrations.AddIndex(
            model_name='personnellocationentry',
            index=models.Index(fields=['timestamp'], name='mentor_trac_timesta_8e434c_idx'),
        ),
        migrations.AddIndex(
            model_name='personnellocationentry',
            index=models.Index(fields=['-timestamp'], name='mentor_trac_timesta_058949_idx'),
        ),
        migrations.AddIndex(
            model_name='personnellocationentry',
            index=models.Index(fields=['personnel', 'location'], name='mentor_trac_personn_f0ad8e_idx'),
        ),
        migrations.AddIndex(
            model_name='personnellocationentry',
            index=models.Index(fields=['personnel', 'location', 'signal_strength'], name='mentor_trac_personn_98f164_idx'),
        ),
        migrations.AddIndex(
            model_name='personnellocationentry',
            index=models.Index(fields=['personnel', 'location', 'timestamp'], name='mentor_trac_personn_a62988_idx'),
        ),
    ]
