# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT tracker_app.wsgi

beta_settings:
    cloud_sql_instances: mentor-tracker:us-central1:mentor-tracker-postgres

runtime_config:
  python_version: 3

handlers:
- url: /*
  secure: always
  redirect_http_response_code: 301
  script: auto

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  cpu_utilization:
    target_utilization: 0.5
# [END django_app]
